version: '3.9'
services:
  db:
    image: mariadb:10.4
    container_name: db
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql/

  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    restart: always
    ports:
      - 8080:80
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
